### PR TITLE
Use a temporary branch for the persister to fix config error

### PR DESCRIPTION
**Pull request by timothyb89**
monasca-persister started treating the `ip_address` config option as
a strict IP address and failed validation when we passed it a
hostname.

For now we'll switch the persister to use a temporary branch while we
wait for the fix to merge.

### CODE REVIEW

**Comment by timothyb89** [comment]
side note: we need to make sure to update `.env` when this merges, we didn't catch this because we're still testing against a build from June 😃

**Comment by kornicameister** [comment]
@timothyb89 @mhoppal Should help you out ;-) => https://review.openstack.org/513259

**Comment by kornicameister** [comment]
Already merged => https://github.com/openstack/monasca-persister/commit/66fe6f98c079490d2d5de4c161da1d8b3801cda4

**Comment by timothyb89** [comment]
Thanks, will just update the persister now :smiley:

**Pull request closed without merging**
