### PR TITLE
Check Keystone status when starting keystone-init

### PR DESCRIPTION
**Pull request by matrixik**
Before initialising Keystone make sure it's working.

### CODE REVIEW

**Comment by matrixik** [comment]
First small change to make sure I'm understanding how all of this works.

**Comment by matrixik** [comment]
Related: #164

**Comment by kornicameister** [comment]
Isn't like this issue will resolve_ #164 ?

**Comment by matrixik** [comment]
No, keystone-init still doesn't support adding endpoints and services.

**Comment by kornicameister** [comment]
don't you think you should call this new method :D

**Comment by matrixik** [comment]
Fixed.

**Comment by timothyb89** [comment]
For what it's worth keystone-init will already retry the initial connection to keystone due to the `@retry()` annotation, though the number of attempts/delay probably should be increased for `get_keystone_client` because we expect it to fail more often: https://github.com/monasca/monasca-docker/blob/e89c2c789a5e280186ca117d1668e057c03c51da/keystone-init/keystone_init.py#L134-L137

That said, we can add an additional check if you think it would help.

**Comment by matrixik** [comment]
Hmmm, you are right. I will just increase numbers for `get_keystone_client`.

**Comment by matrixik** [comment]
Updated with same numbers like in other checks.

**Pull request merged**
