### PR TITLE
Sync containers time with host time

### PR DESCRIPTION
**Pull request by matrixik**
This will link host machine time to time in the containers so we will have same time in docker output logs.

### CODE REVIEW

**Comment by matrixik** [comment]
Done

**Comment by kornicameister** [comment]
@timothyb89 works ok for me, all the timestamp everywhere feature the host timestamp.
if you feel like this is nice addition, please merge :)

**Comment by timothyb89** [comment]
Hmm, I think we'd prefer to keep timestamps as UTC by default. Maybe we could make this optional? e.g. an override .yaml (`docker-compose -f docker-compose.yml -f local-time.yml`) or document the change somewhere?

**Comment by kornicameister** [comment]
I think I'd opt for the documentation, simply because we would need to have overrides for each service and it would make it a bit cumbersome to apprehend. Documentation, however, that would show how we can achieve that with appropriate extension file sounds much more user friendly.

**Comment by matrixik** [comment]
Looks like to provide this separate file I would need to create to separate files: `local-time.yml` and `local-time-log.yml` because I can't add both of them into one file. With one file `docker-compose -f docker-compose.yml -f local-time.yml` will fail because:
```
ERROR: The Compose file is invalid because:
Service kibana has neither an image nor a build context specified. At least one must be provided.
```
I'm not sure if I want to add two separate files for such task.

I can see 3 ways forward:
1. I could add two files if you think is fine
2. I could add only one file with log pipeline commented out
3. I can only add info to documentation about this

@timothyb89 Thoughts?

**Comment by kornicameister** [comment]
With all those problems, I'd opt for documentation solution.
In overall, I believe that docker-compose files here are only relevant for this repository and CI deployment, for all other cases we should craft the compose file on our own to have it suits the needs the best way.

+1 for docs

**Comment by timothyb89** [comment]
Docs seems reasonable to me as well. Thanks!

**Comment by matrixik** [comment]
Changes to `yaml` files removed, added info to README.

**Pull request merged**
