### PR TITLE
Make Grafana admin user configurable

### PR DESCRIPTION
**Pull request by haruki-yamanashi**
The initialization file for grafana was not configurable by using
enrironmental variables during the startup of the container. This commit
makes it possible to configure Grafana admin user name and password of
the file.

### CODE REVIEW

**Comment by timothyb89** [comment]
@matrixik I agree, we should keep them separate from Grafana's [built-in variables](http://docs.grafana.org/installation/configuration/)

**Comment by timothyb89** [comment]
I think this looks good, but if we want to publish a new image `build.yml` needs to be updated with an incremented version (`-1.1.1` to `-1.1.2` or so). Otherwise, feel free to merge.

**Comment by matrixik** [comment]
Version bumped in #215

**Pull request merged**
