### PR TITLE
exclude non file types

### LINKED ISSUE #246: template_dir() function in storm/entrypoint.sh tries to copy directories
The current check in storm/entrypoint.sh currently checks that the file exists in $src_dir.  It is sort of redundant with the loop elements that are elements of a directory.  In addition, the function will fail if a directory exists within src_dir at the "cp" stage later on.

```
template_dir() {
  src_dir=$1
  dest_dir=$2

  for f in "$src_dir"/*; do
   if [ ! -e "$f" ]; then  # <- here
      continue
    fi
```

### PR DESCRIPTION
**Pull request by nseyvet**
Use [ ! -f "$f" ] to assert files instead of  [ ! -e "$f" ]

Closes #246

### CODE REVIEW

**Comment by nseyvet** [comment]
Two problems: 1) Can not figure out how to add files to this pull request; 2) https://github.com/monasca/monasca-docker/blob/master/monasca-thresh/Dockerfile#L1 refers to `FROM monasca/storm:1.0.3`
Ie an inconsistent value with what is available in the build.yml:
```
variants:
  - tag: 1.0.3-1.0.5
```
So I could update the tag to:
```
variants:
  - tag: 1.0.3-1.0.6
```
But I dont understand what to modify in the monasca-thresh Dockerfile?

**Comment by matrixik** [comment]
Ad 1) You bumped version to the same that is on master: https://github.com/monasca/monasca-docker/blob/master/storm/build.yml
You need to bump to `1.0.3-1.0.6`.

Ad 2) On monasca-docker `master` branch I see `FROM monasca/storm:1.0.3-1.0.5` so you just need to change 5 to 6 here.

**Comment by nseyvet** [comment]
Is it OK now?

Sorry for inconvenience.

**Comment by matrixik** [comment]
Sorry, but you pushed to the wrong branch. You need to push to `patch-3` in your fork.

**Comment by matrixik** [comment]
And no problem, I'm here to help you.

**Comment by nseyvet** [comment]
Thank you.

From a pure commit it looks better now I think.  

But 1) CI fails, 2) merge is non-trivial w master.

**Comment by matrixik** [comment]
Ehhh, looks like https://github.com/timothyb89/dbuild script we use for automatically push new images to Docker Hub is not smart enough...
Looks like change in `monasca-thresh/Dockerfile` will need to be added in separate PR after this change is merged and pushed to Docker Hub.

Sorry for all inconvenience.

**Comment by nseyvet** [comment]
It is a good learning experience.  Thank you for baby sitting me 👍

**Comment by matrixik** [comment]
Looks like you got hit by https://github.com/timothyb89/dbuild/issues/2

**Comment by nseyvet** [comment]
CI is green.

**Comment by matrixik** [comment]
I squashed all commits into one for simpler history.

**Pull request merged**
