### PR TITLE
bump storm version

### PR DESCRIPTION
**Pull request by nseyvet**
see #246

Caused by https://github.com/timothyb89/dbuild/issues/2

### CODE REVIEW

**Comment by nseyvet** [comment]
Aligning monasca-thresh with build.yml in storm fails in CI.  I can not identify the error, seems to be during the tempests part, not sure.  Threshold does start, so it is unlikely that the error is due to the version bump...
 ```
4386 [main] INFO  m.t.ThresholdingEngine - -------- Version Information --------
2017-10-13T12:28:12.709145683Z 4417 [main] INFO  m.t.ThresholdingEngine - monasca-thresh-2.1.1-SNAPSHOT-2017-10-13T12:25:15-5c1fd5
2017-10-13T12:28:12.724239540Z 4432 [main] INFO  m.t.ThresholdingEngine - Instantiating ThresholdingEngine with config file: /storm/conf/thresh-config.yml, topology: thresh-cluster
2017-10-13T12:28:14.721366526Z 6430 [main] INFO  o.h.v.i.u.Version - HV000001: Hibernate Validator 5.2.1.Final
```

Any ideas?

**Comment by timothyb89** [comment]
Hmm, odd. Looks like everything passed but the CI script never quit. I just restarted the job, we'll see what happens.

**Comment by kornicameister** [comment]
We've merged #230, I've submitted #254 .
I think that we can close this PR as it uses the older version of the **monasca/storm** image.

**Comment by matrixik** [comment]
We will bump straight to newer version so closing this one.
Thank you.

**Pull request closed without merging**
