### PR TITLE
[fix] Monasca Log API health-check in Dockerfile

### PR DESCRIPTION
**Pull request by chersicm**
Refer to [this issue](https://github.com/monasca/monasca-docker/issues/365).

Also made a couple options configurable via environment variables.

### CODE REVIEW

**Comment by chersicm** [comment]
Thanks, will the official [docker image](https://hub.docker.com/r/monasca/log-api/) be rebuilt right away?

**Comment by matrixik** [comment]
I added `!push monasca-log-api` into merge commit so it should be updated by CI: https://travis-ci.org/monasca/monasca-docker/builds/313460977

**Comment by chersicm** [comment]
Great, thank you!

**Comment by matrixik** [comment]
Images updated. We have a bug in CI that both pipelines upload new images https://github.com/monasca/monasca-docker/issues/272 so don't be confused that there are image that are few minutes apart.

**Pull request merged**
